version: "3.8"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: microblog
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Manila
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
      # Add MySQL configuration directly through volume
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: 'phpmyadmin:latest'
    ports:
      - 8081:80
    links:
      - "db:db"
    depends_on:
      - db

  web:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        PHP_MODE: production
    depends_on: [ db, redis ]
    ports:
      - "8000:80"
    restart: unless-stopped
    volumes:
      - .:/var/www/html:cached
      - vendor:/var/www/html/vendor
    environment:
      PHP_MEMORY_LIMIT: 2G
      PHP_MAX_EXECUTION_TIME: 300
      PHP_OPCACHE_ENABLE: 1
      PHP_REALPATH_CACHE_SIZE: 4096K
      PHP_REALPATH_CACHE_TTL: 600
      COMPOSER_MEMORY_LIMIT: -1

  redis:
    image: redis:alpine
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru

volumes:
  db:
  vendor:
